### Site Settings ###
title               : Faza Iman Imron
description         : >-
                      Nelson Mandela *~* "Education is the most powerful weapon which you can use to change the world."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : fazaimron27/fazaimron27.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Faza Iman Imron
  image             : https://avatars3.githubusercontent.com/u/34373124?s=460&u=10c652a8f6e8c518d43c34b6976a179f66ada87a&v=4
  # behance           : your_username
  # dribbble          : your_username
  dev               : fazaimron27
  email             : cincaumyself@gmail.com
  facebook          : fazaimanimron
  github            : fazaimron27
  instagram         : faza_imron27
  medium            : fazaimron27
  # gitlab            : your_username
  # kaggle            : your_username
  linkedin          : fazaimron27
  # soundcloud        : your_username
  # spotify           : your_username
  # stackoverflow     : your_user_id
  # tumblr            : your_username.tumblr.com
  # twitch            : your_username
  # twitter           : your_username
  # vimeo             : your_username
  # youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus: fazaimron27                         # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
